create extension if not exists pgcrypto with schema extensions;

create table if not exists public.license_admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'founder',
    created_at timestamptz not null default now(),
    check (role in ('founder', 'admin'))
);

alter table public.license_admins enable row level security;
revoke all on public.license_admins from anon, authenticated;

create or replace function public.is_license_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select
        lower(coalesce(auth.jwt() ->> 'email', '')) in (
            '2008yashirchavez@gmail.com',
            'emmajestevex@gmail.com',
            'grego23500@gmail.com'
        )
        or exists (
            select 1
            from public.license_admins
            where user_id = auth.uid()
        );
$$;

insert into public.license_admins (user_id, role)
select id, 'founder'
from auth.users
where lower(email) in (
    '2008yashirchavez@gmail.com',
    'emmajestevex@gmail.com',
    'grego23500@gmail.com'
)
on conflict (user_id) do update
set role = excluded.role;

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'tryhard-content',
    'tryhard-content',
    false,
    104857600,
    null
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.remote_content_files (
    id uuid primary key default extensions.gen_random_uuid(),
    slug text unique not null,
    name text not null,
    description text,
    category text not null default 'files',
    target_bundle text not null default 'com.dts.freefireth',
    target_path text not null,
    version integer not null default 1,
    storage_path text not null,
    file_name text not null,
    mime_type text,
    byte_size bigint not null default 0,
    sha256 text not null,
    is_active boolean not null default true,
    deleted_at timestamptz,
    published_at timestamptz,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (version > 0),
    check (byte_size >= 0),
    check (target_bundle <> ''),
    check (target_path <> ''),
    check (sha256 ~* '^[a-f0-9]{64}$')
);

create table if not exists public.remote_content_releases (
    id bigint generated by default as identity primary key,
    version integer unique not null,
    manifest jsonb not null,
    published_by uuid references auth.users(id) on delete set null,
    published_at timestamptz not null default now(),
    check (version >= 0)
);

create index if not exists remote_content_files_slug_idx
on public.remote_content_files (slug);

create index if not exists remote_content_files_active_idx
on public.remote_content_files (is_active, deleted_at);

create index if not exists remote_content_releases_version_idx
on public.remote_content_releases (version desc);

alter table public.remote_content_files enable row level security;
alter table public.remote_content_releases enable row level security;

revoke all on public.remote_content_files from anon, authenticated;
revoke all on public.remote_content_releases from anon, authenticated;

drop policy if exists "TRYHARD content read for app" on storage.objects;
drop policy if exists "TRYHARD content admin manage" on storage.objects;

create policy "TRYHARD content read for app"
on storage.objects
for select
to anon, authenticated
using (
    bucket_id = 'tryhard-content'
    and name like 'content/%'
);

create policy "TRYHARD content admin manage"
on storage.objects
for all
to authenticated
using (
    bucket_id = 'tryhard-content'
    and name like 'content/%'
    and public.is_license_admin()
)
with check (
    bucket_id = 'tryhard-content'
    and name like 'content/%'
    and public.is_license_admin()
);

create or replace function public.remote_content_safe_slug(p_value text, p_fallback text default 'file')
returns text
language plpgsql
immutable
as $$
declare
    v_slug text;
begin
    v_slug := lower(regexp_replace(trim(coalesce(p_value, '')), '[^a-zA-Z0-9._-]+', '-', 'g'));
    v_slug := trim(both '-' from v_slug);
    v_slug := trim(both '.' from v_slug);

    if v_slug = '' then
        v_slug := lower(regexp_replace(trim(coalesce(p_fallback, 'file')), '[^a-zA-Z0-9._-]+', '-', 'g'));
        v_slug := trim(both '-' from v_slug);
        v_slug := trim(both '.' from v_slug);
    end if;

    if v_slug = '' then
        v_slug := 'file';
    end if;

    return left(v_slug, 80);
end;
$$;

create or replace function public.remote_content_safe_path(
    p_value text,
    p_category text default 'files',
    p_file_name text default 'content.bin'
)
returns text
language plpgsql
immutable
as $$
declare
    v_path text;
begin
    v_path := trim(coalesce(p_value, ''));
    v_path := replace(v_path, E'\\', '/');
    v_path := regexp_replace(v_path, '[^a-zA-Z0-9._/~+-]+', '-', 'g');
    v_path := regexp_replace(v_path, '/+', '/', 'g');
    v_path := trim(both '/' from v_path);

    if v_path = '' then
        v_path := public.remote_content_safe_slug(coalesce(p_category, 'files'), 'files')
            || '/'
            || public.remote_content_safe_slug(coalesce(p_file_name, 'content.bin'), 'content.bin');
    end if;

    if v_path = '' or v_path ~ '(^|/)\.\.(/|$)' then
        raise exception 'Invalid target path';
    end if;

    if v_path !~ '/' or v_path !~ '\.[a-zA-Z0-9~+-]+$' then
        raise exception 'Target path must include a folder and file name';
    end if;

    return left(v_path, 180);
end;
$$;

create or replace function public.remote_content_safe_bundle(p_value text)
returns text
language plpgsql
immutable
as $$
declare
    v_bundle text;
begin
    v_bundle := lower(trim(coalesce(p_value, 'com.dts.freefireth')));

    if v_bundle not in ('com.dts.freefireth', 'com.dts.freefiremax') then
        raise exception 'Invalid target bundle';
    end if;

    return v_bundle;
end;
$$;

alter table public.remote_content_files
add column if not exists target_path text;

alter table public.remote_content_files
add column if not exists target_bundle text;

update public.remote_content_files
set target_bundle = public.remote_content_safe_bundle(target_bundle)
where target_bundle is null
   or trim(target_bundle) = '';

update public.remote_content_files
set target_path = public.remote_content_safe_path(target_path, category, file_name)
where target_path is null
   or trim(target_path) = '';

alter table public.remote_content_files
alter column target_path set not null;

alter table public.remote_content_files
alter column target_bundle set default 'com.dts.freefireth',
alter column target_bundle set not null;

drop index if exists public.remote_content_files_target_path_idx;
drop index if exists public.remote_content_files_target_bundle_path_idx;

create index if not exists remote_content_files_target_bundle_path_idx
on public.remote_content_files (target_bundle, target_path)
where deleted_at is null;

drop function if exists public.admin_list_remote_content_files();

create or replace function public.admin_list_remote_content_files()
returns table (
    id uuid,
    slug text,
    name text,
    description text,
    category text,
    target_bundle text,
    target_path text,
    version integer,
    storage_path text,
    file_name text,
    mime_type text,
    byte_size bigint,
    sha256 text,
    is_active boolean,
    sync_state text,
    deleted_at timestamptz,
    published_at timestamptz,
    created_at timestamptz,
    updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    return query
    select
        f.id,
        f.slug,
        f.name,
        f.description,
        f.category,
        f.target_bundle,
        f.target_path,
        f.version,
        f.storage_path,
        f.file_name,
        f.mime_type,
        f.byte_size,
        f.sha256,
        f.is_active,
        case
            when f.deleted_at is not null then 'delete_pending'
            when f.published_at is null then 'new_pending'
            when f.updated_at > f.published_at then 'change_pending'
            else 'published'
        end as sync_state,
        f.deleted_at,
        f.published_at,
        f.created_at,
        f.updated_at
    from public.remote_content_files f
    where f.deleted_at is null
       or f.updated_at > coalesce(f.published_at, 'epoch'::timestamptz)
    order by f.updated_at desc, f.name asc;
end;
$$;

drop function if exists public.admin_upsert_remote_content_file(text, text, text, text, text, bigint, text, text, text, uuid);
drop function if exists public.admin_upsert_remote_content_file(text, text, text, text, text, text, bigint, text, text, text, uuid);
drop function if exists public.admin_upsert_remote_content_file(text, text, text, text, text, text, text, bigint, text, text, text, uuid);
drop function if exists public.admin_upsert_remote_content_file(text, text, text, text, text, text, text, bigint, text, text, text, uuid, boolean);

create or replace function public.admin_upsert_remote_content_file(
    p_name text,
    p_slug text,
    p_category text,
    p_target_bundle text,
    p_target_path text,
    p_file_name text,
    p_mime_type text,
    p_byte_size bigint,
    p_sha256 text,
    p_storage_path text,
    p_description text default null,
    p_id uuid default null,
    p_force_new boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_name text := nullif(trim(coalesce(p_name, '')), '');
    v_slug text := public.remote_content_safe_slug(p_slug, p_name);
    v_category text := public.remote_content_safe_slug(coalesce(p_category, 'files'), 'files');
    v_target_bundle text := public.remote_content_safe_bundle(p_target_bundle);
    v_file_name text := nullif(trim(coalesce(p_file_name, '')), '');
    v_target_path text := public.remote_content_safe_path(p_target_path, p_category, p_file_name);
    v_mime_type text := nullif(trim(coalesce(p_mime_type, '')), '');
    v_storage_path text := trim(coalesce(p_storage_path, ''));
    v_sha text := lower(trim(coalesce(p_sha256, '')));
    v_file public.remote_content_files%rowtype;
    v_base_slug text;
    v_suffix integer := 2;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_name is null or v_file_name is null then
        raise exception 'Name and file name are required';
    end if;

    if coalesce(p_byte_size, -1) < 0 then
        raise exception 'Invalid file size';
    end if;

    if v_sha !~ '^[a-f0-9]{64}$' then
        raise exception 'Invalid SHA-256';
    end if;

    if v_storage_path = ''
       or v_storage_path like '/%'
       or v_storage_path !~ '^content/'
       or v_storage_path ~ '(^|/)\.\.(/|$)' then
        raise exception 'Invalid storage path';
    end if;

    if p_id is not null then
        select *
        into v_file
        from public.remote_content_files
        where id = p_id
        limit 1
        for update;
    elsif not coalesce(p_force_new, false) then
        select *
        into v_file
        from public.remote_content_files
        where slug = v_slug
        order by updated_at desc
        limit 1
        for update;
    end if;

    if found then
        update public.remote_content_files
        set
            slug = v_slug,
            name = v_name,
            description = nullif(trim(coalesce(p_description, '')), ''),
            category = v_category,
            target_bundle = v_target_bundle,
            target_path = v_target_path,
            version = v_file.version + 1,
            storage_path = v_storage_path,
            file_name = v_file_name,
            mime_type = v_mime_type,
            byte_size = p_byte_size,
            sha256 = v_sha,
            is_active = true,
            deleted_at = null,
            updated_at = now()
        where id = v_file.id
        returning * into v_file;
    else
        v_base_slug := v_slug;
        while exists (
            select 1
            from public.remote_content_files
            where slug = v_slug
        ) loop
            v_slug := left(v_base_slug, greatest(1, 80 - length('-' || v_suffix::text)))
                || '-'
                || v_suffix::text;
            v_suffix := v_suffix + 1;
        end loop;

        insert into public.remote_content_files (
            slug,
            name,
            description,
            category,
            target_bundle,
            target_path,
            version,
            storage_path,
            file_name,
            mime_type,
            byte_size,
            sha256,
            is_active,
            created_by
        )
        values (
            v_slug,
            v_name,
            nullif(trim(coalesce(p_description, '')), ''),
            v_category,
            v_target_bundle,
            v_target_path,
            1,
            v_storage_path,
            v_file_name,
            v_mime_type,
            p_byte_size,
            v_sha,
            true,
            auth.uid()
        )
        returning * into v_file;
    end if;

    return jsonb_build_object(
        'success', true,
        'message', 'File saved. Publish changes when ready.',
        'file', to_jsonb(v_file)
    );
end;
$$;

create or replace function public.admin_disable_remote_content_target(
    p_name text,
    p_slug text,
    p_category text,
    p_target_bundle text,
    p_target_path text,
    p_description text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_name text := nullif(trim(coalesce(p_name, '')), '');
    v_slug text := public.remote_content_safe_slug(p_slug, p_name);
    v_category text := public.remote_content_safe_slug(coalesce(p_category, 'patches'), 'patches');
    v_target_bundle text := public.remote_content_safe_bundle(p_target_bundle);
    v_target_path text := public.remote_content_safe_path(p_target_path, p_category, 'disabled.bin');
    v_file public.remote_content_files%rowtype;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_name is null then
        raise exception 'Name is required';
    end if;

    select *
    into v_file
    from public.remote_content_files
    where slug = v_slug
       or (target_bundle = v_target_bundle and target_path = v_target_path)
    order by
        case
            when target_bundle = v_target_bundle and target_path = v_target_path then 0
            when slug = v_slug then 1
            else 2
        end
    limit 1
    for update;

    if found then
        update public.remote_content_files
        set
            slug = v_slug,
            name = v_name,
            description = nullif(trim(coalesce(p_description, '')), ''),
            category = v_category,
            target_bundle = v_target_bundle,
            target_path = v_target_path,
            version = v_file.version + 1,
            is_active = false,
            deleted_at = now(),
            updated_at = now()
        where id = v_file.id
        returning * into v_file;
    else
        insert into public.remote_content_files (
            slug,
            name,
            description,
            category,
            target_bundle,
            target_path,
            version,
            storage_path,
            file_name,
            mime_type,
            byte_size,
            sha256,
            is_active,
            deleted_at,
            created_by
        )
        values (
            v_slug,
            v_name,
            nullif(trim(coalesce(p_description, '')), ''),
            v_category,
            v_target_bundle,
            v_target_path,
            1,
            'content/tombstone/empty',
            'removed.txt',
            'text/plain',
            0,
            'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
            false,
            now(),
            auth.uid()
        )
        returning * into v_file;
    end if;

    return jsonb_build_object(
        'success', true,
        'message', 'Target marked for removal. Publish changes when ready.',
        'file', to_jsonb(v_file)
    );
end;
$$;

create or replace function public.admin_set_remote_content_active(
    p_id uuid,
    p_is_active boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_file public.remote_content_files%rowtype;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    update public.remote_content_files
    set
        is_active = coalesce(p_is_active, false),
        deleted_at = null,
        updated_at = now()
    where id = p_id
    returning * into v_file;

    if not found then
        return jsonb_build_object('success', false, 'message', 'File not found');
    end if;

    return jsonb_build_object(
        'success', true,
        'message', 'File status updated. Publish changes when ready.',
        'file', to_jsonb(v_file)
    );
end;
$$;

create or replace function public.admin_delete_remote_content_file(p_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_file public.remote_content_files%rowtype;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    update public.remote_content_files
    set
        is_active = false,
        deleted_at = now(),
        updated_at = now()
    where id = p_id
    returning * into v_file;

    if not found then
        return jsonb_build_object('success', false, 'message', 'File not found');
    end if;

    return jsonb_build_object(
        'success', true,
        'message', 'File marked for deletion. Publish changes when ready.',
        'file', to_jsonb(v_file)
    );
end;
$$;

create or replace function public.admin_publish_remote_content()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_next_version integer;
    v_published_at timestamptz := now();
    v_files jsonb;
    v_manifest jsonb;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    select coalesce(max(version), 0) + 1
    into v_next_version
    from public.remote_content_releases;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', f.id::text,
                'slug', f.slug,
                'name', f.name,
                'description', f.description,
                'category', f.category,
                'target_bundle', f.target_bundle,
                'target_path', f.target_path,
                'version', f.version,
                'storage_path', f.storage_path,
                'file_name', f.file_name,
                'mime_type', f.mime_type,
                'byte_size', f.byte_size,
                'sha256', lower(f.sha256),
                'is_active', f.is_active,
                'deleted_at', f.deleted_at,
                'published_at', v_published_at
            )
            order by f.category, f.name, f.id
        ),
        '[]'::jsonb
    )
    into v_files
    from public.remote_content_files f;

    v_manifest := jsonb_build_object(
        'success', true,
        'message', 'Manifest ready',
        'version', v_next_version,
        'published_at', v_published_at,
        'files', v_files
    );

    insert into public.remote_content_releases (
        version,
        manifest,
        published_by,
        published_at
    )
    values (
        v_next_version,
        v_manifest,
        auth.uid(),
        v_published_at
    );

    update public.remote_content_files f
    set published_at = v_published_at
    where f.published_at is null
       or f.updated_at >= f.published_at
       or f.deleted_at is not null;

    return v_manifest;
end;
$$;

create or replace function public.get_remote_content_manifest(
    p_license_key text,
    p_device_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_license jsonb;
    v_manifest jsonb;
begin
    v_license := public.check_license(p_license_key, p_device_id)::jsonb;

    if coalesce((v_license->>'success')::boolean, false) = false then
        return jsonb_build_object(
            'success', false,
            'message', coalesce(v_license->>'message', 'License check failed'),
            'version', 0,
            'published_at', null,
            'files', jsonb_build_array()
        );
    end if;

    select r.manifest
    into v_manifest
    from public.remote_content_releases r
    order by r.version desc
    limit 1;

    if v_manifest is null then
        return jsonb_build_object(
            'success', true,
            'message', 'No published content yet',
            'version', 0,
            'published_at', null,
            'files', jsonb_build_array()
        );
    end if;

    return v_manifest;
end;
$$;

revoke all on function public.remote_content_safe_slug(text, text) from public;
revoke all on function public.remote_content_safe_path(text, text, text) from public;
revoke all on function public.remote_content_safe_bundle(text) from public;
revoke all on function public.admin_list_remote_content_files() from public;
revoke all on function public.admin_upsert_remote_content_file(text, text, text, text, text, text, text, bigint, text, text, text, uuid, boolean) from public;
revoke all on function public.admin_set_remote_content_active(uuid, boolean) from public;
revoke all on function public.admin_delete_remote_content_file(uuid) from public;
revoke all on function public.admin_disable_remote_content_target(text, text, text, text, text, text) from public;
revoke all on function public.admin_publish_remote_content() from public;
revoke all on function public.get_remote_content_manifest(text, text) from public;

grant execute on function public.admin_list_remote_content_files() to authenticated;
grant execute on function public.is_license_admin() to authenticated;
grant execute on function public.admin_upsert_remote_content_file(text, text, text, text, text, text, text, bigint, text, text, text, uuid, boolean) to authenticated;
grant execute on function public.admin_set_remote_content_active(uuid, boolean) to authenticated;
grant execute on function public.admin_delete_remote_content_file(uuid) to authenticated;
grant execute on function public.admin_disable_remote_content_target(text, text, text, text, text, text) to authenticated;
grant execute on function public.admin_publish_remote_content() to authenticated;
grant execute on function public.get_remote_content_manifest(text, text) to anon, authenticated;
