-- Tryhard full Supabase setup
-- Run this once in Supabase SQL Editor for the TRYHARD project.

-- 1) Licenses and keys
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.licenses (
    id bigint generated by default as identity primary key,
    license_key text unique not null,
    device_id text,
    is_active boolean not null default true,
    activated_at timestamptz,
    used_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.licenses
    add column if not exists device_id text,
    add column if not exists is_active boolean not null default true,
    add column if not exists activated_at timestamptz,
    add column if not exists used_at timestamptz,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists status text not null default 'available',
    add column if not exists label text,
    add column if not exists capabilities jsonb not null default '[]'::jsonb,
    add column if not exists expires_at timestamptz,
    add column if not exists created_by uuid references auth.users(id) on delete set null,
    add column if not exists updated_at timestamptz not null default now();

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'licenses_status_check'
          and conrelid = 'public.licenses'::regclass
    ) then
        alter table public.licenses
            add constraint licenses_status_check
            check (status in ('available', 'active', 'paused', 'blocked', 'expired'));
    end if;
end $$;

create table if not exists public.license_admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'founder',
    created_at timestamptz not null default now(),
    check (role in ('founder', 'admin'))
);

alter table public.licenses enable row level security;
alter table public.license_admins enable row level security;

revoke all on public.licenses from anon, authenticated;
revoke all on public.license_admins from anon, authenticated;

update public.licenses
set
    status = 'active',
    used_at = coalesce(used_at, activated_at, now()),
    is_active = true,
    updated_at = now()
where status = 'available'
  and (device_id is not null or activated_at is not null or used_at is not null);

update public.licenses
set
    status = 'blocked',
    is_active = false,
    updated_at = now()
where license_key ~ '^TRYHARD-[0-9]+$';

insert into public.licenses (license_key, label, capabilities, status, is_active)
values (
    'TRYHARD-ESPECIAL927394HD',
    'Special TIO key',
    '["special_assetindexer"]'::jsonb,
    'available',
    true
)
on conflict (license_key) do update
set
    label = excluded.label,
    capabilities = excluded.capabilities,
    status = case
        when public.licenses.used_at is null
         and public.licenses.device_id is null
         and public.licenses.activated_at is null
        then 'available'
        else public.licenses.status
    end,
    is_active = case
        when public.licenses.used_at is null
         and public.licenses.device_id is null
         and public.licenses.activated_at is null
        then true
        when public.licenses.status in ('blocked', 'paused', 'expired') then false
        else true
    end,
    updated_at = now();

create or replace function public.normalize_license_key(p_license_key text)
returns text
language sql
immutable
as $$
    select upper(regexp_replace(trim(coalesce(p_license_key, '')), '\s+', '', 'g'));
$$;

create or replace function public.generate_secure_license_key(p_prefix text default 'TRYHARD')
returns text
language plpgsql
as $$
declare
    v_prefix text := upper(regexp_replace(trim(coalesce(p_prefix, 'TRYHARD')), '[^A-Z0-9]+', '', 'g'));
    v_raw text := encode(extensions.gen_random_bytes(12), 'hex');
begin
    if v_prefix = '' then
        v_prefix := 'TRYHARD';
    end if;

    return v_prefix || '-' ||
        upper(substr(v_raw, 1, 4) || '-' ||
              substr(v_raw, 5, 4) || '-' ||
              substr(v_raw, 9, 4) || '-' ||
              substr(v_raw, 13, 4) || '-' ||
              substr(v_raw, 17, 4) || '-' ||
              substr(v_raw, 21, 4));
end;
$$;

create or replace function public.is_license_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select
        lower(coalesce(auth.jwt() ->> 'email', '')) in (
            '2008yashirchavez@gmail.com',
            'emmajestevex@gmail.com',
            'grego23500@gmail.com'
        )
        or exists (
            select 1
            from public.license_admins
            where user_id = auth.uid()
        );
$$;

insert into public.license_admins (user_id, role)
select id, 'founder'
from auth.users
where lower(email) in (
    '2008yashirchavez@gmail.com',
    'emmajestevex@gmail.com',
    'grego23500@gmail.com'
)
on conflict (user_id) do update
set role = excluded.role;

create or replace function public.license_status_message(p_status text)
returns text
language sql
immutable
as $$
    select case p_status
        when 'paused' then 'Key paused'
        when 'blocked' then 'Key blocked'
        when 'expired' then 'Key expired'
        else 'Key unavailable'
    end;
$$;

create or replace function public.activate_license(
    p_license_key text,
    p_device_id text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_license public.licenses%rowtype;
    v_key text;
    v_device text := trim(coalesce(p_device_id, ''));
begin
    v_key := public.normalize_license_key(p_license_key);

    if v_key = '' or v_device = '' then
        return json_build_object('success', false, 'message', 'Invalid key', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    if v_key ~ '^TRYHARD-[0-9]+$' then
        return json_build_object('success', false, 'message', 'Old numeric keys are disabled', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    select *
    into v_license
    from public.licenses
    where license_key = v_key
    for update;

    if not found then
        return json_build_object('success', false, 'message', 'Invalid key', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    if v_license.expires_at is not null and v_license.expires_at <= now() then
        update public.licenses
        set status = 'expired', is_active = false, updated_at = now()
        where id = v_license.id;

        return json_build_object('success', false, 'message', 'Key expired', 'capabilities', json_build_array(), 'expires_at', v_license.expires_at);
    end if;

    if v_license.status in ('paused', 'blocked', 'expired') or v_license.is_active = false then
        return json_build_object(
            'success', false,
            'message', public.license_status_message(v_license.status),
            'capabilities', json_build_array(),
            'expires_at', v_license.expires_at
        );
    end if;

    if v_license.status = 'active'
       and v_license.device_id = v_device
       and v_license.is_active = true then
        return json_build_object(
            'success', true,
            'message', 'Key verified',
            'capabilities', coalesce(v_license.capabilities, '[]'::jsonb),
            'expires_at', v_license.expires_at
        );
    end if;

    if v_license.status <> 'available'
        or v_license.used_at is not null
        or v_license.device_id is not null
        or v_license.activated_at is not null then
        return json_build_object(
            'success', false,
            'message', 'This key has already been used',
            'capabilities', json_build_array(),
            'expires_at', v_license.expires_at
        );
    end if;

    update public.licenses
    set
        device_id = v_device,
        activated_at = now(),
        used_at = now(),
        status = 'active',
        is_active = true,
        updated_at = now()
    where id = v_license.id
    returning * into v_license;

    return json_build_object(
        'success', true,
        'message', 'Key activated successfully',
        'capabilities', coalesce(v_license.capabilities, '[]'::jsonb),
        'expires_at', v_license.expires_at
    );
end;
$$;

create or replace function public.check_license(
    p_license_key text,
    p_device_id text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_license public.licenses%rowtype;
    v_key text;
    v_device text := trim(coalesce(p_device_id, ''));
begin
    v_key := public.normalize_license_key(p_license_key);

    if v_key = '' or v_device = '' then
        return json_build_object('success', false, 'message', 'Invalid key', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    if v_key ~ '^TRYHARD-[0-9]+$' then
        return json_build_object('success', false, 'message', 'Old numeric keys are disabled', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    select *
    into v_license
    from public.licenses
    where license_key = v_key
    for update;

    if not found then
        return json_build_object('success', false, 'message', 'Invalid key', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    if v_license.expires_at is not null and v_license.expires_at <= now() then
        update public.licenses
        set status = 'expired', is_active = false, updated_at = now()
        where id = v_license.id;

        return json_build_object('success', false, 'message', 'Key expired', 'capabilities', json_build_array(), 'expires_at', v_license.expires_at);
    end if;

    if v_license.status in ('paused', 'blocked', 'expired') or v_license.is_active = false then
        return json_build_object(
            'success', false,
            'message', public.license_status_message(v_license.status),
            'capabilities', json_build_array(),
            'expires_at', v_license.expires_at
        );
    end if;

    if v_license.status <> 'active' or v_license.device_id is null then
        return json_build_object('success', false, 'message', 'Key is not active on this device', 'capabilities', json_build_array(), 'expires_at', v_license.expires_at);
    end if;

    if v_license.device_id <> v_device then
        return json_build_object('success', false, 'message', 'This key is already used on another device', 'capabilities', json_build_array(), 'expires_at', v_license.expires_at);
    end if;

    return json_build_object(
        'success', true,
        'message', 'Key verified',
        'capabilities', coalesce(v_license.capabilities, '[]'::jsonb),
        'expires_at', v_license.expires_at
    );
end;
$$;

create or replace function public.admin_generate_licenses(
    p_quantity integer default 1,
    p_duration_hours integer default null,
    p_label text default null,
    p_capabilities jsonb default '[]'::jsonb,
    p_custom_license_key text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_quantity integer := greatest(1, least(coalesce(p_quantity, 1), 200));
    v_capabilities jsonb := coalesce(p_capabilities, '[]'::jsonb);
    v_duration integer := p_duration_hours;
    v_expires_at timestamptz := null;
    v_keys text[] := array[]::text[];
    v_key text;
    v_custom text := public.normalize_license_key(p_custom_license_key);
    i integer;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if jsonb_typeof(v_capabilities) <> 'array' then
        raise exception 'Capabilities must be a JSON array';
    end if;

    if exists (
        select 1
        from jsonb_array_elements_text(v_capabilities) as capability(value)
        where capability.value <> 'special_assetindexer'
    ) then
        raise exception 'Unsupported license capability';
    end if;

    if v_duration is not null and v_duration > 0 then
        v_expires_at := now() + make_interval(hours => v_duration);
    end if;

    if v_custom <> '' then
        if v_quantity <> 1 then
            raise exception 'Custom keys can only be created one at a time';
        end if;

        if v_custom ~ '^TRYHARD-[0-9]+$' then
            raise exception 'Old numeric key format is disabled';
        end if;

        v_key := null;
        insert into public.licenses (license_key, label, capabilities, expires_at, created_by, status, is_active)
        values (v_custom, nullif(trim(coalesce(p_label, '')), ''), v_capabilities, v_expires_at, auth.uid(), 'available', true)
        on conflict (license_key) do update
        set
            label = excluded.label,
            capabilities = excluded.capabilities,
            expires_at = excluded.expires_at,
            updated_at = now()
        where public.licenses.used_at is null
          and public.licenses.device_id is null
          and public.licenses.activated_at is null
        returning license_key into v_key;

        if v_key is null then
            raise exception 'Custom key already exists and has been used';
        end if;

        v_keys := array_append(v_keys, v_custom);
    else
        for i in 1..v_quantity loop
            loop
                v_key := public.generate_secure_license_key('TRYHARD');
                begin
                    insert into public.licenses (license_key, label, capabilities, expires_at, created_by, status, is_active)
                    values (v_key, nullif(trim(coalesce(p_label, '')), ''), v_capabilities, v_expires_at, auth.uid(), 'available', true);
                    v_keys := array_append(v_keys, v_key);
                    exit;
                exception when unique_violation then
                end;
            end loop;
        end loop;
    end if;

    return json_build_object(
        'success', true,
        'message', 'Keys generated',
        'keys', v_keys,
        'expires_at', v_expires_at
    );
end;
$$;

create or replace function public.admin_list_licenses()
returns table (
    license_key text,
    status text,
    label text,
    device_id text,
    activated_at timestamptz,
    used_at timestamptz,
    expires_at timestamptz,
    capabilities jsonb,
    created_at timestamptz,
    updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    update public.licenses as l
    set status = 'expired', is_active = false, updated_at = now()
    where l.expires_at is not null
      and l.expires_at <= now()
      and l.status not in ('blocked', 'expired');

    return query
    select
        l.license_key,
        l.status,
        l.label,
        l.device_id,
        l.activated_at,
        l.used_at,
        l.expires_at,
        coalesce(l.capabilities, '[]'::jsonb),
        l.created_at,
        l.updated_at
    from public.licenses l
    order by l.created_at desc, l.id desc;
end;
$$;

create or replace function public.admin_set_license_status(
    p_license_key text,
    p_status text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_key text := public.normalize_license_key(p_license_key);
    v_status text := lower(trim(coalesce(p_status, '')));
    v_license public.licenses%rowtype;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_key = '' or v_status not in ('available', 'active', 'paused', 'blocked', 'expired') then
        return json_build_object('success', false, 'message', 'Invalid request');
    end if;

    select *
    into v_license
    from public.licenses
    where license_key = v_key
    for update;

    if not found then
        return json_build_object('success', false, 'message', 'Key not found');
    end if;

    if v_status = 'available'
       and (v_license.used_at is not null or v_license.device_id is not null or v_license.activated_at is not null) then
        return json_build_object('success', false, 'message', 'Used keys cannot be reset to available');
    end if;

    if v_status = 'active' and v_license.device_id is null then
        v_status := 'available';
    end if;

    update public.licenses
    set
        status = v_status,
        expires_at = case
            when v_status in ('available', 'active')
             and v_license.expires_at is not null
             and v_license.expires_at <= now() then null
            else expires_at
        end,
        is_active = v_status in ('available', 'active'),
        updated_at = now()
    where id = v_license.id
    returning * into v_license;

    return json_build_object(
        'success', true,
        'message', 'Key updated',
        'license_key', v_license.license_key,
        'status', v_license.status
    );
end;
$$;

create or replace function public.admin_set_license_expiration(
    p_license_key text,
    p_expires_at timestamptz
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_key text := public.normalize_license_key(p_license_key);
    v_status text;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_key = '' then
        return json_build_object('success', false, 'message', 'Invalid key');
    end if;

    update public.licenses as l
    set
        expires_at = p_expires_at,
        status = case
            when p_expires_at is not null and p_expires_at <= now() then 'expired'
            when l.status = 'expired' and p_expires_at is not null and p_expires_at > now() and l.device_id is not null then 'active'
            when l.status = 'expired' and p_expires_at is not null and p_expires_at > now() and l.device_id is null then 'available'
            else l.status
        end,
        is_active = case
            when p_expires_at is not null and p_expires_at <= now() then false
            when l.status in ('blocked', 'paused') then false
            else true
        end,
        updated_at = now()
    where l.license_key = v_key
    returning l.status into v_status;

    if not found then
        return json_build_object('success', false, 'message', 'Key not found');
    end if;

    return json_build_object(
        'success', true,
        'message', 'Expiration updated',
        'license_key', v_key,
        'status', v_status,
        'expires_at', p_expires_at
    );
end;
$$;

create or replace function public.admin_delete_license(
    p_license_key text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_key text := public.normalize_license_key(p_license_key);
    v_status text;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_key = '' then
        return json_build_object('success', false, 'message', 'Invalid key');
    end if;

    select status
    into v_status
    from public.licenses
    where license_key = v_key
    for update;

    if not found then
        return json_build_object('success', false, 'message', 'Key not found');
    end if;

    if v_status not in ('blocked', 'expired') then
        return json_build_object('success', false, 'message', 'Only blocked or expired keys can be deleted');
    end if;

    delete from public.licenses
    where license_key = v_key;

    return json_build_object(
        'success', true,
        'message', 'Key deleted',
        'license_key', v_key
    );
end;
$$;

revoke all on function public.normalize_license_key(text) from public;
revoke all on function public.generate_secure_license_key(text) from public;
revoke all on function public.is_license_admin() from public;
revoke all on function public.license_status_message(text) from public;
revoke all on function public.activate_license(text, text) from public;
revoke all on function public.check_license(text, text) from public;
revoke all on function public.admin_generate_licenses(integer, integer, text, jsonb, text) from public;
revoke all on function public.admin_list_licenses() from public;
revoke all on function public.admin_set_license_status(text, text) from public;
revoke all on function public.admin_set_license_expiration(text, timestamptz) from public;
revoke all on function public.admin_delete_license(text) from public;

grant execute on function public.activate_license(text, text) to anon, authenticated;
grant execute on function public.check_license(text, text) to anon, authenticated;
grant execute on function public.is_license_admin() to authenticated;
grant execute on function public.admin_generate_licenses(integer, integer, text, jsonb, text) to authenticated;
grant execute on function public.admin_list_licenses() to authenticated;
grant execute on function public.admin_set_license_status(text, text) to authenticated;
grant execute on function public.admin_set_license_expiration(text, timestamptz) to authenticated;
grant execute on function public.admin_delete_license(text) to authenticated;


-- 2) Remote files and storage bucket
create extension if not exists pgcrypto with schema extensions;

create table if not exists public.license_admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'founder',
    created_at timestamptz not null default now(),
    check (role in ('founder', 'admin'))
);

alter table public.license_admins enable row level security;
revoke all on public.license_admins from anon, authenticated;

create or replace function public.is_license_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select
        lower(coalesce(auth.jwt() ->> 'email', '')) in (
            '2008yashirchavez@gmail.com',
            'emmajestevex@gmail.com',
            'grego23500@gmail.com'
        )
        or exists (
            select 1
            from public.license_admins
            where user_id = auth.uid()
        );
$$;

insert into public.license_admins (user_id, role)
select id, 'founder'
from auth.users
where lower(email) in (
    '2008yashirchavez@gmail.com',
    'emmajestevex@gmail.com',
    'grego23500@gmail.com'
)
on conflict (user_id) do update
set role = excluded.role;

insert into storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
values (
    'tryhard-content',
    'tryhard-content',
    false,
    104857600,
    null
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create table if not exists public.remote_content_files (
    id uuid primary key default extensions.gen_random_uuid(),
    slug text unique not null,
    name text not null,
    description text,
    category text not null default 'files',
    target_bundle text not null default 'com.dts.freefireth',
    target_path text not null,
    version integer not null default 1,
    storage_path text not null,
    file_name text not null,
    mime_type text,
    byte_size bigint not null default 0,
    sha256 text not null,
    is_active boolean not null default true,
    deleted_at timestamptz,
    published_at timestamptz,
    created_by uuid references auth.users(id) on delete set null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (version > 0),
    check (byte_size >= 0),
    check (target_bundle <> ''),
    check (target_path <> ''),
    check (sha256 ~* '^[a-f0-9]{64}$')
);

create table if not exists public.remote_content_releases (
    id bigint generated by default as identity primary key,
    version integer unique not null,
    manifest jsonb not null,
    published_by uuid references auth.users(id) on delete set null,
    published_at timestamptz not null default now(),
    check (version >= 0)
);

create index if not exists remote_content_files_slug_idx
on public.remote_content_files (slug);

create index if not exists remote_content_files_active_idx
on public.remote_content_files (is_active, deleted_at);

create index if not exists remote_content_releases_version_idx
on public.remote_content_releases (version desc);

alter table public.remote_content_files enable row level security;
alter table public.remote_content_releases enable row level security;

revoke all on public.remote_content_files from anon, authenticated;
revoke all on public.remote_content_releases from anon, authenticated;

drop policy if exists "TRYHARD content read for app" on storage.objects;
drop policy if exists "TRYHARD content admin manage" on storage.objects;

create policy "TRYHARD content read for app"
on storage.objects
for select
to anon, authenticated
using (
    bucket_id = 'tryhard-content'
    and name like 'content/%'
);

create policy "TRYHARD content admin manage"
on storage.objects
for all
to authenticated
using (
    bucket_id = 'tryhard-content'
    and name like 'content/%'
    and public.is_license_admin()
)
with check (
    bucket_id = 'tryhard-content'
    and name like 'content/%'
    and public.is_license_admin()
);

create or replace function public.remote_content_safe_slug(p_value text, p_fallback text default 'file')
returns text
language plpgsql
immutable
as $$
declare
    v_slug text;
begin
    v_slug := lower(regexp_replace(trim(coalesce(p_value, '')), '[^a-zA-Z0-9._-]+', '-', 'g'));
    v_slug := trim(both '-' from v_slug);
    v_slug := trim(both '.' from v_slug);

    if v_slug = '' then
        v_slug := lower(regexp_replace(trim(coalesce(p_fallback, 'file')), '[^a-zA-Z0-9._-]+', '-', 'g'));
        v_slug := trim(both '-' from v_slug);
        v_slug := trim(both '.' from v_slug);
    end if;

    if v_slug = '' then
        v_slug := 'file';
    end if;

    return left(v_slug, 80);
end;
$$;

create or replace function public.remote_content_safe_path(
    p_value text,
    p_category text default 'files',
    p_file_name text default 'content.bin'
)
returns text
language plpgsql
immutable
as $$
declare
    v_path text;
begin
    v_path := trim(coalesce(p_value, ''));
    v_path := replace(v_path, E'\\', '/');
    v_path := regexp_replace(v_path, '[^a-zA-Z0-9._/~+-]+', '-', 'g');
    v_path := regexp_replace(v_path, '/+', '/', 'g');
    v_path := trim(both '/' from v_path);

    if v_path = '' then
        v_path := public.remote_content_safe_slug(coalesce(p_category, 'files'), 'files')
            || '/'
            || public.remote_content_safe_slug(coalesce(p_file_name, 'content.bin'), 'content.bin');
    end if;

    if v_path = '' or v_path ~ '(^|/)\.\.(/|$)' then
        raise exception 'Invalid target path';
    end if;

    if v_path !~ '/' or v_path !~ '\.[a-zA-Z0-9~+-]+$' then
        raise exception 'Target path must include a folder and file name';
    end if;

    return left(v_path, 180);
end;
$$;

create or replace function public.remote_content_safe_bundle(p_value text)
returns text
language plpgsql
immutable
as $$
declare
    v_bundle text;
begin
    v_bundle := lower(trim(coalesce(p_value, 'com.dts.freefireth')));

    if v_bundle not in ('com.dts.freefireth', 'com.dts.freefiremax') then
        raise exception 'Invalid target bundle';
    end if;

    return v_bundle;
end;
$$;

alter table public.remote_content_files
add column if not exists target_path text;

alter table public.remote_content_files
add column if not exists target_bundle text;

update public.remote_content_files
set target_bundle = public.remote_content_safe_bundle(target_bundle)
where target_bundle is null
   or trim(target_bundle) = '';

update public.remote_content_files
set target_path = public.remote_content_safe_path(target_path, category, file_name)
where target_path is null
   or trim(target_path) = '';

alter table public.remote_content_files
alter column target_path set not null;

alter table public.remote_content_files
alter column target_bundle set default 'com.dts.freefireth',
alter column target_bundle set not null;

drop index if exists public.remote_content_files_target_path_idx;
drop index if exists public.remote_content_files_target_bundle_path_idx;

create index if not exists remote_content_files_target_bundle_path_idx
on public.remote_content_files (target_bundle, target_path)
where deleted_at is null;

drop function if exists public.admin_list_remote_content_files();

create or replace function public.admin_list_remote_content_files()
returns table (
    id uuid,
    slug text,
    name text,
    description text,
    category text,
    target_bundle text,
    target_path text,
    version integer,
    storage_path text,
    file_name text,
    mime_type text,
    byte_size bigint,
    sha256 text,
    is_active boolean,
    sync_state text,
    deleted_at timestamptz,
    published_at timestamptz,
    created_at timestamptz,
    updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    return query
    select
        f.id,
        f.slug,
        f.name,
        f.description,
        f.category,
        f.target_bundle,
        f.target_path,
        f.version,
        f.storage_path,
        f.file_name,
        f.mime_type,
        f.byte_size,
        f.sha256,
        f.is_active,
        case
            when f.deleted_at is not null then 'delete_pending'
            when f.published_at is null then 'new_pending'
            when f.updated_at > f.published_at then 'change_pending'
            else 'published'
        end as sync_state,
        f.deleted_at,
        f.published_at,
        f.created_at,
        f.updated_at
    from public.remote_content_files f
    where f.deleted_at is null
       or f.updated_at > coalesce(f.published_at, 'epoch'::timestamptz)
    order by f.updated_at desc, f.name asc;
end;
$$;

drop function if exists public.admin_upsert_remote_content_file(text, text, text, text, text, bigint, text, text, text, uuid);
drop function if exists public.admin_upsert_remote_content_file(text, text, text, text, text, text, bigint, text, text, text, uuid);
drop function if exists public.admin_upsert_remote_content_file(text, text, text, text, text, text, text, bigint, text, text, text, uuid);
drop function if exists public.admin_upsert_remote_content_file(text, text, text, text, text, text, text, bigint, text, text, text, uuid, boolean);

create or replace function public.admin_upsert_remote_content_file(
    p_name text,
    p_slug text,
    p_category text,
    p_target_bundle text,
    p_target_path text,
    p_file_name text,
    p_mime_type text,
    p_byte_size bigint,
    p_sha256 text,
    p_storage_path text,
    p_description text default null,
    p_id uuid default null,
    p_force_new boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_name text := nullif(trim(coalesce(p_name, '')), '');
    v_slug text := public.remote_content_safe_slug(p_slug, p_name);
    v_category text := public.remote_content_safe_slug(coalesce(p_category, 'files'), 'files');
    v_target_bundle text := public.remote_content_safe_bundle(p_target_bundle);
    v_file_name text := nullif(trim(coalesce(p_file_name, '')), '');
    v_target_path text := public.remote_content_safe_path(p_target_path, p_category, p_file_name);
    v_mime_type text := nullif(trim(coalesce(p_mime_type, '')), '');
    v_storage_path text := trim(coalesce(p_storage_path, ''));
    v_sha text := lower(trim(coalesce(p_sha256, '')));
    v_file public.remote_content_files%rowtype;
    v_base_slug text;
    v_suffix integer := 2;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_name is null or v_file_name is null then
        raise exception 'Name and file name are required';
    end if;

    if coalesce(p_byte_size, -1) < 0 then
        raise exception 'Invalid file size';
    end if;

    if v_sha !~ '^[a-f0-9]{64}$' then
        raise exception 'Invalid SHA-256';
    end if;

    if v_storage_path = ''
       or v_storage_path like '/%'
       or v_storage_path !~ '^content/'
       or v_storage_path ~ '(^|/)\.\.(/|$)' then
        raise exception 'Invalid storage path';
    end if;

    if p_id is not null then
        select *
        into v_file
        from public.remote_content_files
        where id = p_id
        limit 1
        for update;
    elsif not coalesce(p_force_new, false) then
        select *
        into v_file
        from public.remote_content_files
        where slug = v_slug
        order by updated_at desc
        limit 1
        for update;
    end if;

    if found then
        update public.remote_content_files
        set
            slug = v_slug,
            name = v_name,
            description = nullif(trim(coalesce(p_description, '')), ''),
            category = v_category,
            target_bundle = v_target_bundle,
            target_path = v_target_path,
            version = v_file.version + 1,
            storage_path = v_storage_path,
            file_name = v_file_name,
            mime_type = v_mime_type,
            byte_size = p_byte_size,
            sha256 = v_sha,
            is_active = true,
            deleted_at = null,
            updated_at = now()
        where id = v_file.id
        returning * into v_file;
    else
        v_base_slug := v_slug;
        while exists (
            select 1
            from public.remote_content_files
            where slug = v_slug
        ) loop
            v_slug := left(v_base_slug, greatest(1, 80 - length('-' || v_suffix::text)))
                || '-'
                || v_suffix::text;
            v_suffix := v_suffix + 1;
        end loop;

        insert into public.remote_content_files (
            slug,
            name,
            description,
            category,
            target_bundle,
            target_path,
            version,
            storage_path,
            file_name,
            mime_type,
            byte_size,
            sha256,
            is_active,
            created_by
        )
        values (
            v_slug,
            v_name,
            nullif(trim(coalesce(p_description, '')), ''),
            v_category,
            v_target_bundle,
            v_target_path,
            1,
            v_storage_path,
            v_file_name,
            v_mime_type,
            p_byte_size,
            v_sha,
            true,
            auth.uid()
        )
        returning * into v_file;
    end if;

    return jsonb_build_object(
        'success', true,
        'message', 'File saved. Publish changes when ready.',
        'file', to_jsonb(v_file)
    );
end;
$$;

create or replace function public.admin_disable_remote_content_target(
    p_name text,
    p_slug text,
    p_category text,
    p_target_bundle text,
    p_target_path text,
    p_description text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_name text := nullif(trim(coalesce(p_name, '')), '');
    v_slug text := public.remote_content_safe_slug(p_slug, p_name);
    v_category text := public.remote_content_safe_slug(coalesce(p_category, 'patches'), 'patches');
    v_target_bundle text := public.remote_content_safe_bundle(p_target_bundle);
    v_target_path text := public.remote_content_safe_path(p_target_path, p_category, 'disabled.bin');
    v_file public.remote_content_files%rowtype;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_name is null then
        raise exception 'Name is required';
    end if;

    select *
    into v_file
    from public.remote_content_files
    where slug = v_slug
       or (target_bundle = v_target_bundle and target_path = v_target_path)
    order by
        case
            when target_bundle = v_target_bundle and target_path = v_target_path then 0
            when slug = v_slug then 1
            else 2
        end
    limit 1
    for update;

    if found then
        update public.remote_content_files
        set
            slug = v_slug,
            name = v_name,
            description = nullif(trim(coalesce(p_description, '')), ''),
            category = v_category,
            target_bundle = v_target_bundle,
            target_path = v_target_path,
            version = v_file.version + 1,
            is_active = false,
            deleted_at = now(),
            updated_at = now()
        where id = v_file.id
        returning * into v_file;
    else
        insert into public.remote_content_files (
            slug,
            name,
            description,
            category,
            target_bundle,
            target_path,
            version,
            storage_path,
            file_name,
            mime_type,
            byte_size,
            sha256,
            is_active,
            deleted_at,
            created_by
        )
        values (
            v_slug,
            v_name,
            nullif(trim(coalesce(p_description, '')), ''),
            v_category,
            v_target_bundle,
            v_target_path,
            1,
            'content/tombstone/empty',
            'removed.txt',
            'text/plain',
            0,
            'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
            false,
            now(),
            auth.uid()
        )
        returning * into v_file;
    end if;

    return jsonb_build_object(
        'success', true,
        'message', 'Target marked for removal. Publish changes when ready.',
        'file', to_jsonb(v_file)
    );
end;
$$;

create or replace function public.admin_set_remote_content_active(
    p_id uuid,
    p_is_active boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_file public.remote_content_files%rowtype;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    update public.remote_content_files
    set
        is_active = coalesce(p_is_active, false),
        deleted_at = null,
        updated_at = now()
    where id = p_id
    returning * into v_file;

    if not found then
        return jsonb_build_object('success', false, 'message', 'File not found');
    end if;

    return jsonb_build_object(
        'success', true,
        'message', 'File status updated. Publish changes when ready.',
        'file', to_jsonb(v_file)
    );
end;
$$;

create or replace function public.admin_delete_remote_content_file(p_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_file public.remote_content_files%rowtype;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    update public.remote_content_files
    set
        is_active = false,
        deleted_at = now(),
        updated_at = now()
    where id = p_id
    returning * into v_file;

    if not found then
        return jsonb_build_object('success', false, 'message', 'File not found');
    end if;

    return jsonb_build_object(
        'success', true,
        'message', 'File marked for deletion. Publish changes when ready.',
        'file', to_jsonb(v_file)
    );
end;
$$;

create or replace function public.admin_publish_remote_content()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_next_version integer;
    v_published_at timestamptz := now();
    v_files jsonb;
    v_manifest jsonb;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    select coalesce(max(version), 0) + 1
    into v_next_version
    from public.remote_content_releases;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'id', f.id::text,
                'slug', f.slug,
                'name', f.name,
                'description', f.description,
                'category', f.category,
                'target_bundle', f.target_bundle,
                'target_path', f.target_path,
                'version', f.version,
                'storage_path', f.storage_path,
                'file_name', f.file_name,
                'mime_type', f.mime_type,
                'byte_size', f.byte_size,
                'sha256', lower(f.sha256),
                'is_active', f.is_active,
                'deleted_at', f.deleted_at,
                'published_at', v_published_at
            )
            order by f.category, f.name, f.id
        ),
        '[]'::jsonb
    )
    into v_files
    from public.remote_content_files f;

    v_manifest := jsonb_build_object(
        'success', true,
        'message', 'Manifest ready',
        'version', v_next_version,
        'published_at', v_published_at,
        'files', v_files
    );

    insert into public.remote_content_releases (
        version,
        manifest,
        published_by,
        published_at
    )
    values (
        v_next_version,
        v_manifest,
        auth.uid(),
        v_published_at
    );

    update public.remote_content_files f
    set published_at = v_published_at
    where f.published_at is null
       or f.updated_at >= f.published_at
       or f.deleted_at is not null;

    return v_manifest;
end;
$$;

create or replace function public.get_remote_content_manifest(
    p_license_key text,
    p_device_id text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_license jsonb;
    v_manifest jsonb;
begin
    v_license := public.check_license(p_license_key, p_device_id)::jsonb;

    if coalesce((v_license->>'success')::boolean, false) = false then
        return jsonb_build_object(
            'success', false,
            'message', coalesce(v_license->>'message', 'License check failed'),
            'version', 0,
            'published_at', null,
            'files', jsonb_build_array()
        );
    end if;

    select r.manifest
    into v_manifest
    from public.remote_content_releases r
    order by r.version desc
    limit 1;

    if v_manifest is null then
        return jsonb_build_object(
            'success', true,
            'message', 'No published content yet',
            'version', 0,
            'published_at', null,
            'files', jsonb_build_array()
        );
    end if;

    return v_manifest;
end;
$$;

revoke all on function public.remote_content_safe_slug(text, text) from public;
revoke all on function public.remote_content_safe_path(text, text, text) from public;
revoke all on function public.remote_content_safe_bundle(text) from public;
revoke all on function public.admin_list_remote_content_files() from public;
revoke all on function public.admin_upsert_remote_content_file(text, text, text, text, text, text, text, bigint, text, text, text, uuid, boolean) from public;
revoke all on function public.admin_set_remote_content_active(uuid, boolean) from public;
revoke all on function public.admin_delete_remote_content_file(uuid) from public;
revoke all on function public.admin_disable_remote_content_target(text, text, text, text, text, text) from public;
revoke all on function public.admin_publish_remote_content() from public;
revoke all on function public.get_remote_content_manifest(text, text) from public;

grant execute on function public.admin_list_remote_content_files() to authenticated;
grant execute on function public.is_license_admin() to authenticated;
grant execute on function public.admin_upsert_remote_content_file(text, text, text, text, text, text, text, bigint, text, text, text, uuid, boolean) to authenticated;
grant execute on function public.admin_set_remote_content_active(uuid, boolean) to authenticated;
grant execute on function public.admin_delete_remote_content_file(uuid) to authenticated;
grant execute on function public.admin_disable_remote_content_target(text, text, text, text, text, text) to authenticated;
grant execute on function public.admin_publish_remote_content() to authenticated;
grant execute on function public.get_remote_content_manifest(text, text) to anon, authenticated;


-- 3) Admin emails
create table if not exists public.license_admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'founder',
    created_at timestamptz not null default now(),
    check (role in ('founder', 'admin'))
);

alter table public.license_admins enable row level security;

create or replace function public.is_license_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select
        lower(coalesce(auth.jwt() ->> 'email', '')) in (
            '2008yashirchavez@gmail.com',
            'emmajestevex@gmail.com',
            'grego23500@gmail.com'
        )
        or exists (
            select 1
            from public.license_admins
            where user_id = auth.uid()
        );
$$;

insert into public.license_admins (user_id, role)
select id, 'founder'
from auth.users
where lower(email) in (
    '2008yashirchavez@gmail.com',
    'emmajestevex@gmail.com',
    'grego23500@gmail.com'
)
on conflict (user_id) do update
set role = excluded.role;

grant execute on function public.is_license_admin() to authenticated;

-- 4) Known Tryhard test key from the current device test.
-- Safe to rerun: if the key already exists, it keeps the row active and labeled.
insert into public.licenses (license_key, label, capabilities, status, is_active)
values (
    'TRYHARD-7281-265D-6D5B-6CDD-39CC-F3AD',
    '[tryhard] PRUEBA',
    '[]'::jsonb,
    'available',
    true
)
on conflict (license_key) do update
set
    label = coalesce(public.licenses.label, excluded.label),
    capabilities = coalesce(public.licenses.capabilities, excluded.capabilities),
    is_active = true,
    updated_at = now();

-- 5) Final backend audit. The SQL editor should return true values here.
select
    to_regclass('public.licenses') is not null as has_licenses,
    to_regclass('public.remote_content_files') is not null as has_remote_content_files,
    to_regclass('public.remote_content_releases') is not null as has_remote_content_releases,
    exists(select 1 from storage.buckets where id = 'tryhard-content') as has_tryhard_content_bucket,
    to_regprocedure('public.activate_license(text,text)') is not null as has_activate_license,
    to_regprocedure('public.check_license(text,text)') is not null as has_check_license,
    to_regprocedure('public.get_remote_content_manifest(text,text)') is not null as has_remote_manifest,
    to_regprocedure('public.admin_publish_remote_content()') is not null as has_admin_publish_remote_content;

