-- TRYHARD KEYS BACKEND REQUIRED
-- Run this full file in Supabase SQL Editor for https://gvnrcivehodixrvvtevl.supabase.co

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.licenses (
    id bigint generated by default as identity primary key,
    license_key text unique not null,
    device_id text,
    is_active boolean not null default true,
    activated_at timestamptz,
    used_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.licenses
    add column if not exists device_id text,
    add column if not exists is_active boolean not null default true,
    add column if not exists activated_at timestamptz,
    add column if not exists used_at timestamptz,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists status text not null default 'available',
    add column if not exists label text,
    add column if not exists capabilities jsonb not null default '[]'::jsonb,
    add column if not exists expires_at timestamptz,
    add column if not exists created_by uuid references auth.users(id) on delete set null,
    add column if not exists updated_at timestamptz not null default now();

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'licenses_status_check'
          and conrelid = 'public.licenses'::regclass
    ) then
        alter table public.licenses
            add constraint licenses_status_check
            check (status in ('available', 'active', 'paused', 'blocked', 'expired'));
    end if;
end $$;

create table if not exists public.license_admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    role text not null default 'founder',
    created_at timestamptz not null default now(),
    check (role in ('founder', 'admin'))
);

alter table public.licenses enable row level security;
alter table public.license_admins enable row level security;

revoke all on public.licenses from anon, authenticated;
revoke all on public.license_admins from anon, authenticated;

update public.licenses
set
    status = 'active',
    used_at = coalesce(used_at, activated_at, now()),
    is_active = true,
    updated_at = now()
where status = 'available'
  and (device_id is not null or activated_at is not null or used_at is not null);

update public.licenses
set
    status = 'blocked',
    is_active = false,
    updated_at = now()
where license_key ~ '^TRYHARD-[0-9]+$';

insert into public.licenses (license_key, label, capabilities, status, is_active)
values (
    'TRYHARD-ESPECIAL927394HD',
    'Special TIO key',
    '["special_assetindexer"]'::jsonb,
    'available',
    true
)
on conflict (license_key) do update
set
    label = excluded.label,
    capabilities = excluded.capabilities,
    status = case
        when public.licenses.used_at is null
         and public.licenses.device_id is null
         and public.licenses.activated_at is null
        then 'available'
        else public.licenses.status
    end,
    is_active = case
        when public.licenses.used_at is null
         and public.licenses.device_id is null
         and public.licenses.activated_at is null
        then true
        when public.licenses.status in ('blocked', 'paused', 'expired') then false
        else true
    end,
    updated_at = now();

create or replace function public.normalize_license_key(p_license_key text)
returns text
language sql
immutable
as $$
    select upper(regexp_replace(trim(coalesce(p_license_key, '')), '\s+', '', 'g'));
$$;

create or replace function public.generate_secure_license_key(p_prefix text default 'TRYHARD')
returns text
language plpgsql
as $$
declare
    v_prefix text := upper(regexp_replace(trim(coalesce(p_prefix, 'TRYHARD')), '[^A-Z0-9]+', '', 'g'));
    v_raw text := encode(extensions.gen_random_bytes(12), 'hex');
begin
    if v_prefix = '' then
        v_prefix := 'TRYHARD';
    end if;

    return v_prefix || '-' ||
        upper(substr(v_raw, 1, 4) || '-' ||
              substr(v_raw, 5, 4) || '-' ||
              substr(v_raw, 9, 4) || '-' ||
              substr(v_raw, 13, 4) || '-' ||
              substr(v_raw, 17, 4) || '-' ||
              substr(v_raw, 21, 4));
end;
$$;

create or replace function public.is_license_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
    select
        lower(coalesce(auth.jwt() ->> 'email', '')) in (
            '2008yashirchavez@gmail.com',
            'emmajestevex@gmail.com',
            'grego23500@gmail.com'
        )
        or exists (
            select 1
            from public.license_admins
            where user_id = auth.uid()
        );
$$;

insert into public.license_admins (user_id, role)
select id, 'founder'
from auth.users
where lower(email) in (
    '2008yashirchavez@gmail.com',
    'emmajestevex@gmail.com',
    'grego23500@gmail.com'
)
on conflict (user_id) do update
set role = excluded.role;

create or replace function public.license_status_message(p_status text)
returns text
language sql
immutable
as $$
    select case p_status
        when 'paused' then 'Key paused'
        when 'blocked' then 'Key blocked'
        when 'expired' then 'Key expired'
        else 'Key unavailable'
    end;
$$;

create or replace function public.activate_license(
    p_license_key text,
    p_device_id text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_license public.licenses%rowtype;
    v_key text;
    v_device text := trim(coalesce(p_device_id, ''));
begin
    v_key := public.normalize_license_key(p_license_key);

    if v_key = '' or v_device = '' then
        return json_build_object('success', false, 'message', 'Invalid key', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    if v_key ~ '^TRYHARD-[0-9]+$' then
        return json_build_object('success', false, 'message', 'Old numeric keys are disabled', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    select *
    into v_license
    from public.licenses
    where license_key = v_key
    for update;

    if not found then
        return json_build_object('success', false, 'message', 'Invalid key', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    if v_license.expires_at is not null and v_license.expires_at <= now() then
        update public.licenses
        set status = 'expired', is_active = false, updated_at = now()
        where id = v_license.id;

        return json_build_object('success', false, 'message', 'Key expired', 'capabilities', json_build_array(), 'expires_at', v_license.expires_at);
    end if;

    if v_license.status in ('paused', 'blocked', 'expired') or v_license.is_active = false then
        return json_build_object(
            'success', false,
            'message', public.license_status_message(v_license.status),
            'capabilities', json_build_array(),
            'expires_at', v_license.expires_at
        );
    end if;

    if v_license.status = 'active'
       and v_license.device_id = v_device
       and v_license.is_active = true then
        return json_build_object(
            'success', true,
            'message', 'Key verified',
            'capabilities', coalesce(v_license.capabilities, '[]'::jsonb),
            'expires_at', v_license.expires_at
        );
    end if;

    if v_license.status <> 'available'
        or v_license.used_at is not null
        or v_license.device_id is not null
        or v_license.activated_at is not null then
        return json_build_object(
            'success', false,
            'message', 'This key has already been used',
            'capabilities', json_build_array(),
            'expires_at', v_license.expires_at
        );
    end if;

    update public.licenses
    set
        device_id = v_device,
        activated_at = now(),
        used_at = now(),
        status = 'active',
        is_active = true,
        updated_at = now()
    where id = v_license.id
    returning * into v_license;

    return json_build_object(
        'success', true,
        'message', 'Key activated successfully',
        'capabilities', coalesce(v_license.capabilities, '[]'::jsonb),
        'expires_at', v_license.expires_at
    );
end;
$$;

create or replace function public.check_license(
    p_license_key text,
    p_device_id text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_license public.licenses%rowtype;
    v_key text;
    v_device text := trim(coalesce(p_device_id, ''));
begin
    v_key := public.normalize_license_key(p_license_key);

    if v_key = '' or v_device = '' then
        return json_build_object('success', false, 'message', 'Invalid key', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    if v_key ~ '^TRYHARD-[0-9]+$' then
        return json_build_object('success', false, 'message', 'Old numeric keys are disabled', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    select *
    into v_license
    from public.licenses
    where license_key = v_key
    for update;

    if not found then
        return json_build_object('success', false, 'message', 'Invalid key', 'capabilities', json_build_array(), 'expires_at', null);
    end if;

    if v_license.expires_at is not null and v_license.expires_at <= now() then
        update public.licenses
        set status = 'expired', is_active = false, updated_at = now()
        where id = v_license.id;

        return json_build_object('success', false, 'message', 'Key expired', 'capabilities', json_build_array(), 'expires_at', v_license.expires_at);
    end if;

    if v_license.status in ('paused', 'blocked', 'expired') or v_license.is_active = false then
        return json_build_object(
            'success', false,
            'message', public.license_status_message(v_license.status),
            'capabilities', json_build_array(),
            'expires_at', v_license.expires_at
        );
    end if;

    if v_license.status <> 'active' or v_license.device_id is null then
        return json_build_object('success', false, 'message', 'Key is not active on this device', 'capabilities', json_build_array(), 'expires_at', v_license.expires_at);
    end if;

    if v_license.device_id <> v_device then
        return json_build_object('success', false, 'message', 'This key is already used on another device', 'capabilities', json_build_array(), 'expires_at', v_license.expires_at);
    end if;

    return json_build_object(
        'success', true,
        'message', 'Key verified',
        'capabilities', coalesce(v_license.capabilities, '[]'::jsonb),
        'expires_at', v_license.expires_at
    );
end;
$$;

create or replace function public.admin_generate_licenses(
    p_quantity integer default 1,
    p_duration_hours integer default null,
    p_label text default null,
    p_capabilities jsonb default '[]'::jsonb,
    p_custom_license_key text default null
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_quantity integer := greatest(1, least(coalesce(p_quantity, 1), 200));
    v_capabilities jsonb := coalesce(p_capabilities, '[]'::jsonb);
    v_duration integer := p_duration_hours;
    v_expires_at timestamptz := null;
    v_keys text[] := array[]::text[];
    v_key text;
    v_custom text := public.normalize_license_key(p_custom_license_key);
    i integer;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if jsonb_typeof(v_capabilities) <> 'array' then
        raise exception 'Capabilities must be a JSON array';
    end if;

    if exists (
        select 1
        from jsonb_array_elements_text(v_capabilities) as capability(value)
        where capability.value <> 'special_assetindexer'
    ) then
        raise exception 'Unsupported license capability';
    end if;

    if v_duration is not null and v_duration > 0 then
        v_expires_at := now() + make_interval(hours => v_duration);
    end if;

    if v_custom <> '' then
        if v_quantity <> 1 then
            raise exception 'Custom keys can only be created one at a time';
        end if;

        if v_custom ~ '^TRYHARD-[0-9]+$' then
            raise exception 'Old numeric key format is disabled';
        end if;

        v_key := null;
        insert into public.licenses (license_key, label, capabilities, expires_at, created_by, status, is_active)
        values (v_custom, nullif(trim(coalesce(p_label, '')), ''), v_capabilities, v_expires_at, auth.uid(), 'available', true)
        on conflict (license_key) do update
        set
            label = excluded.label,
            capabilities = excluded.capabilities,
            expires_at = excluded.expires_at,
            updated_at = now()
        where public.licenses.used_at is null
          and public.licenses.device_id is null
          and public.licenses.activated_at is null
        returning license_key into v_key;

        if v_key is null then
            raise exception 'Custom key already exists and has been used';
        end if;

        v_keys := array_append(v_keys, v_custom);
    else
        for i in 1..v_quantity loop
            loop
                v_key := public.generate_secure_license_key('TRYHARD');
                begin
                    insert into public.licenses (license_key, label, capabilities, expires_at, created_by, status, is_active)
                    values (v_key, nullif(trim(coalesce(p_label, '')), ''), v_capabilities, v_expires_at, auth.uid(), 'available', true);
                    v_keys := array_append(v_keys, v_key);
                    exit;
                exception when unique_violation then
                end;
            end loop;
        end loop;
    end if;

    return json_build_object(
        'success', true,
        'message', 'Keys generated',
        'keys', v_keys,
        'expires_at', v_expires_at
    );
end;
$$;

create or replace function public.admin_list_licenses()
returns table (
    license_key text,
    status text,
    label text,
    device_id text,
    activated_at timestamptz,
    used_at timestamptz,
    expires_at timestamptz,
    capabilities jsonb,
    created_at timestamptz,
    updated_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    update public.licenses as l
    set status = 'expired', is_active = false, updated_at = now()
    where l.expires_at is not null
      and l.expires_at <= now()
      and l.status not in ('blocked', 'expired');

    return query
    select
        l.license_key,
        l.status,
        l.label,
        l.device_id,
        l.activated_at,
        l.used_at,
        l.expires_at,
        coalesce(l.capabilities, '[]'::jsonb),
        l.created_at,
        l.updated_at
    from public.licenses l
    order by l.created_at desc, l.id desc;
end;
$$;

create or replace function public.admin_set_license_status(
    p_license_key text,
    p_status text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_key text := public.normalize_license_key(p_license_key);
    v_status text := lower(trim(coalesce(p_status, '')));
    v_license public.licenses%rowtype;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_key = '' or v_status not in ('available', 'active', 'paused', 'blocked', 'expired') then
        return json_build_object('success', false, 'message', 'Invalid request');
    end if;

    select *
    into v_license
    from public.licenses
    where license_key = v_key
    for update;

    if not found then
        return json_build_object('success', false, 'message', 'Key not found');
    end if;

    if v_status = 'available'
       and (v_license.used_at is not null or v_license.device_id is not null or v_license.activated_at is not null) then
        return json_build_object('success', false, 'message', 'Used keys cannot be reset to available');
    end if;

    if v_status = 'active' and v_license.device_id is null then
        v_status := 'available';
    end if;

    update public.licenses
    set
        status = v_status,
        expires_at = case
            when v_status in ('available', 'active')
             and v_license.expires_at is not null
             and v_license.expires_at <= now() then null
            else expires_at
        end,
        is_active = v_status in ('available', 'active'),
        updated_at = now()
    where id = v_license.id
    returning * into v_license;

    return json_build_object(
        'success', true,
        'message', 'Key updated',
        'license_key', v_license.license_key,
        'status', v_license.status
    );
end;
$$;

create or replace function public.admin_set_license_expiration(
    p_license_key text,
    p_expires_at timestamptz
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_key text := public.normalize_license_key(p_license_key);
    v_status text;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_key = '' then
        return json_build_object('success', false, 'message', 'Invalid key');
    end if;

    update public.licenses as l
    set
        expires_at = p_expires_at,
        status = case
            when p_expires_at is not null and p_expires_at <= now() then 'expired'
            when l.status = 'expired' and p_expires_at is not null and p_expires_at > now() and l.device_id is not null then 'active'
            when l.status = 'expired' and p_expires_at is not null and p_expires_at > now() and l.device_id is null then 'available'
            else l.status
        end,
        is_active = case
            when p_expires_at is not null and p_expires_at <= now() then false
            when l.status in ('blocked', 'paused') then false
            else true
        end,
        updated_at = now()
    where l.license_key = v_key
    returning l.status into v_status;

    if not found then
        return json_build_object('success', false, 'message', 'Key not found');
    end if;

    return json_build_object(
        'success', true,
        'message', 'Expiration updated',
        'license_key', v_key,
        'status', v_status,
        'expires_at', p_expires_at
    );
end;
$$;

create or replace function public.admin_delete_license(
    p_license_key text
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_key text := public.normalize_license_key(p_license_key);
    v_status text;
begin
    if not public.is_license_admin() then
        raise exception 'Not authorized';
    end if;

    if v_key = '' then
        return json_build_object('success', false, 'message', 'Invalid key');
    end if;

    select status
    into v_status
    from public.licenses
    where license_key = v_key
    for update;

    if not found then
        return json_build_object('success', false, 'message', 'Key not found');
    end if;

    if v_status not in ('blocked', 'expired') then
        return json_build_object('success', false, 'message', 'Only blocked or expired keys can be deleted');
    end if;

    delete from public.licenses
    where license_key = v_key;

    return json_build_object(
        'success', true,
        'message', 'Key deleted',
        'license_key', v_key
    );
end;
$$;

revoke all on function public.normalize_license_key(text) from public;
revoke all on function public.generate_secure_license_key(text) from public;
revoke all on function public.is_license_admin() from public;
revoke all on function public.license_status_message(text) from public;
revoke all on function public.activate_license(text, text) from public;
revoke all on function public.check_license(text, text) from public;
revoke all on function public.admin_generate_licenses(integer, integer, text, jsonb, text) from public;
revoke all on function public.admin_list_licenses() from public;
revoke all on function public.admin_set_license_status(text, text) from public;
revoke all on function public.admin_set_license_expiration(text, timestamptz) from public;
revoke all on function public.admin_delete_license(text) from public;

grant execute on function public.activate_license(text, text) to anon, authenticated;
grant execute on function public.check_license(text, text) to anon, authenticated;
grant execute on function public.is_license_admin() to authenticated;
grant execute on function public.admin_generate_licenses(integer, integer, text, jsonb, text) to authenticated;
grant execute on function public.admin_list_licenses() to authenticated;
grant execute on function public.admin_set_license_status(text, text) to authenticated;
grant execute on function public.admin_set_license_expiration(text, timestamptz) to authenticated;
grant execute on function public.admin_delete_license(text) to authenticated;

-- Test key requested from the app screenshot.
insert into public.licenses (license_key, label, capabilities, status, is_active)
values (
    'TRYHARD-7281-265D-6D5B-6CDD-39CC-F3AD',
    '[tryhard] PRUEBA',
    '[]'::jsonb,
    'available',
    true
)
on conflict (license_key) do update
set
    label = excluded.label,
    capabilities = excluded.capabilities,
    status = case
        when public.licenses.device_id is null
         and public.licenses.activated_at is null
         and public.licenses.used_at is null
        then 'available'
        else public.licenses.status
    end,
    is_active = case
        when public.licenses.status in ('blocked', 'paused', 'expired') then false
        else true
    end,
    updated_at = now();